# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Qiniu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: |
          npm install -g yarn
          rm -rf .npmrc yarn.lock | true
          yarn install
      - name: Publish
        run: |
          # update and upload plugins.json
          node scripts/getPlugins.js

          # upload plugins
          for p in `ls | grep "plugin-"`; do
            node scripts/publish.js ${p}
          done
        env:
          QINIU_ACCESS_KEY: ${{secrets.QINIU_ACCESS_KEY}}
          QINIU_SECRET_KEY: ${{secrets.QINIU_SECRET_KEY}}
          QINIU_BUCKET: ${{secrets.QINIU_BUCKET}}
          QINIU_ZONE: ${{secrets.QINIU_ZONE}}
